# list of all recipes
help:
    @just -f {{ justfile() }} --list --unsorted

# watch for changes and compile
watch:
    watchexec -e cljs,css just compile

# compile cljs, bundle mjs, and compile css
compile:
    bunx --bun tailwindcss -i src/css/app.css -o ../resources/app.css
    bunx --bun squint compile
    bun build src/js/app.mjs --outfile ../resources/app.js
    touch ../.reload
