((nil . ((cider-preferred-build-tool . clojure-cli)
         (cider-clojure-cli-aliases . ":dev")
         (cider-ns-refresh-before-fn . "user/stop!")
         (cider-ns-refresh-after-fn . "user/start!")
         (cider-ns-code-reload-tool 'clj-reload))))
