name: Tests

on:
  push:
    paths-ignore:
      - "**/*.md"
      - "/.gitignore"
    branches:
      - main

permissions:
  contents: write
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
      - uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: latest
      - name: Prepare local Selmer dependency
        run: clojure -X:deps prep
      - name: Test
        run: clojure -M:test

  tag:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - id: set-artifact-tag-version
        run: echo "ARTIFACT_TAG_VERSION=0.3.$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT
      - id: create-tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.set-artifact-tag-version.outputs.ARTIFACT_TAG_VERSION }}
          force_push_tag: true
